language: python
python: "3.6"

dist: bionic
os: linux

cache:
  directories:
  - $HOME/.cache/tools

before_install: ./tests/scripts/bootstrap.sh
script: .travis/script.sh
after_success:
  - .travis/after_success.sh

jobs:
  include:
    - env: BUILD_TARGET="docker-check" OTBR_COVERAGE=1 VERBOSE=1
    - env: BUILD_TARGET="macOS"
      os: osx
      language: "generic"
  allow_failures:
    - env: BUILD_TARGET="mdns-mojo-check" VERBOSE=1
      os: linux
