language: cpp

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libdbus-1-dev
    - autoconf-archive
    - doxygen
    - ctags
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libavahi-common-dev
    - libavahi-client-dev
    - avahi-daemon
    - expect
    - libjsoncpp-dev

cache:
  directories:
  - $HOME/.cache/tools

before_install: .travis/before_install.sh
script: .travis/script.sh
matrix:
  include:
    - env: BUILD_TARGET="pretty-check"
      os: linux
    - env: BUILD_TARGET="posix-check" VERBOSE=1
      compiler: gcc
      os: linux
